databases:
  - name: smart-quote-db-emax
    databaseName: smart_quote_api_emax
    user: smart_quote_api
    plan: basic-256mb
    region: singapore

services:
  - type: web
    name: smart-quote-api-emax
    runtime: ruby
    rootDir: smart-quote-api
    buildCommand: "bundle install && bundle exec rails db:prepare"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    region: singapore
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: smart-quote-db-emax
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: 'true'
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: CORS_ORIGINS
        value: 'https://smart-quote-emax.vercel.app'
      - key: FRONTEND_URL
        value: 'https://smart-quote-emax.vercel.app'
      - key: MAILER_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /up
